// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4avVb74srqT7fMRRClDDi_yYFSULy378',
    appId: '1:999374234370:web:7dbb3d68b4ed39e30ad81b',
    messagingSenderId: '999374234370',
    projectId: 'fina-9fea8',
    authDomain: 'fina-9fea8.firebaseapp.com',
    storageBucket: 'fina-9fea8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMvKNxjuOvaWU7BkXpN0NNTgjIvUwMIwA',
    appId: '1:999374234370:android:fd6ee1d7f5923f430ad81b',
    messagingSenderId: '999374234370',
    projectId: 'fina-9fea8',
    storageBucket: 'fina-9fea8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxnmKu3JoNxi001tYo0zz8WSfPU0WAW0U',
    appId: '1:999374234370:ios:6a979e37bcfc8ac80ad81b',
    messagingSenderId: '999374234370',
    projectId: 'fina-9fea8',
    storageBucket: 'fina-9fea8.firebasestorage.app',
    iosBundleId: 'com.example.fina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxnmKu3JoNxi001tYo0zz8WSfPU0WAW0U',
    appId: '1:999374234370:ios:6a979e37bcfc8ac80ad81b',
    messagingSenderId: '999374234370',
    projectId: 'fina-9fea8',
    storageBucket: 'fina-9fea8.firebasestorage.app',
    iosBundleId: 'com.example.fina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4avVb74srqT7fMRRClDDi_yYFSULy378',
    appId: '1:999374234370:web:af4e04a6e00de1e20ad81b',
    messagingSenderId: '999374234370',
    projectId: 'fina-9fea8',
    authDomain: 'fina-9fea8.firebaseapp.com',
    storageBucket: 'fina-9fea8.firebasestorage.app',
  );
}
